-- Insert sample purchase data
INSERT INTO purchases (title, description, category, amount, supplier, "invoiceNumber", "paymentMethod", "purchaseDate", "expectedDeliveryDate", "requestedBy", status, notes)
VALUES
(
    'Materiales de Oficina',
    'Compra de papelería básica para el inicio del año escolar: papel, bolígrafos, carpetas, etc.',
    'office_supplies',
    150000,
    'Papelería Central',
    'FAC-001-2024',
    'bank_transfer',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '7 days',
    (SELECT id FROM users LIMIT 1),
    'approved',
    'Materiales necesarios para el funcionamiento administrativo'
),
(
    'Libros de Texto',
    'Libros de texto para las materias de matemáticas y ciencias naturales',
    'educational_materials',
    500000,
    'Editorial Educativa',
    'FAC-002-2024',
    'check',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '15 days',
    (SELECT id FROM users LIMIT 1),
    'pending',
    'Libros para estudiantes de primaria'
),
(
    'Equipos de Computación',
    'Laptops para el laboratorio de informática',
    'technology',
    2500000,
    'TecnoStore',
    'FAC-003-2024',
    'credit_card',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '30 days',
    (SELECT id FROM users LIMIT 1),
    'completed',
    'Equipos para modernizar el laboratorio'
),
(
    'Servicios de Limpieza',
    'Productos de limpieza y desinfección para el colegio',
    'cleaning_supplies',
    200000,
    'Limpieza Total',
    'FAC-004-2024',
    'cash',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '3 days',
    (SELECT id FROM users LIMIT 1),
    'approved',
    'Productos para mantener la higiene del colegio'
),
(
    'Mantenimiento de Infraestructura',
    'Reparación de techos y pintura de aulas',
    'maintenance',
    800000,
    'Constructora ABC',
    'FAC-005-2024',
    'bank_transfer',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '20 days',
    (SELECT id FROM users LIMIT 1),
    'rejected',
    'Proyecto de mejoramiento de infraestructura'
),
(
    'Servicio de Transporte',
    'Contratación de servicio de transporte escolar',
    'transportation',
    1200000,
    'Transportes Escolares',
    'FAC-006-2024',
    'bank_transfer',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '10 days',
    (SELECT id FROM users LIMIT 1),
    'pending',
    'Servicio para estudiantes de zonas alejadas'
),
(
    'Servicios de Alimentación',
    'Contrato de servicio de cafetería y comedor',
    'food_services',
    600000,
    'Catering Escolar',
    'FAC-007-2024',
    'check',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '5 days',
    (SELECT id FROM users LIMIT 1),
    'cancelled',
    'Servicio de alimentación para estudiantes'
),
(
    'Equipos Deportivos',
    'Balones, redes y equipos para educación física',
    'other',
    300000,
    'Deportes y Más',
    'FAC-008-2024',
    'cash',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '7 days',
    (SELECT id FROM users LIMIT 1),
    'approved',
    'Equipos para actividades deportivas'
)
ON CONFLICT DO NOTHING;
